# Generated by Django 4.2.9 on 2024-01-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discription1',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='discription2',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='discription3',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='discription4',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='discription5',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
