# Generated by Django 4.2.9 on 2024-01-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_is_special_alter_blog_discription1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_None1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_None2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_None3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_None4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_None5',
        ),
    ]
