# Generated by Django 4.2.9 on 2024-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discription', models.TextField(max_length=158)),
                ('main_title', models.CharField(max_length=100)),
                ('main_discription', models.TextField(max_length=2500)),
                ('is_None1', models.BooleanField(default=False)),
                ('title1', models.CharField(max_length=100)),
                ('discription1', models.TextField(max_length=2500)),
                ('is_None2', models.BooleanField(default=False)),
                ('title2', models.CharField(max_length=100)),
                ('discription2', models.TextField(max_length=2500)),
                ('is_None3', models.BooleanField(default=False)),
                ('title3', models.CharField(max_length=100)),
                ('discription3', models.TextField(max_length=2500)),
                ('is_None4', models.BooleanField(default=False)),
                ('title4', models.CharField(max_length=100)),
                ('discription4', models.TextField(max_length=2500)),
                ('is_None5', models.BooleanField(default=False)),
                ('title5', models.CharField(max_length=100)),
                ('discription5', models.TextField(max_length=2500)),
                ('is_special', models.BooleanField(default=False)),
                ('picture', models.ImageField(upload_to='static/image/')),
            ],
        ),
    ]
