# Generated by Django 4.2.9 on 2024-01-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_discription1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_None1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_None2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_None3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_None4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_None5',
        ),
    ]
