# Generated by Django 4.2.9 on 2024-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='representatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('address', models.TextField(max_length=110)),
                ('phone', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
