# Generated by Django 4.2.9 on 2024-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='name',
            field=models.CharField(max_length=23),
        ),
    ]
