# Generated by Django 4.2.9 on 2024-01-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_representatives_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='representatives',
            new_name='represent',
        ),
    ]
